server {
    listen 8070;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /shoptrace {
        try_files $uri $uri/ /index.html;
    }
}
