receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1
    timeout: 1s

exporters:
  otlp/gateway:
    endpoint: "otel-backend-nlb-56216bb3ab8b8c79.elb.us-east-1.amazonaws.com:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]