extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  debug:

  otlp_http/nlb:
    endpoint: http://otel-gateway-nlb-3b88104205cc8ef6.elb.us-east-1.amazonaws.com:4318

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_http/nlb]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_http/nlb]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_http/nlb]